### ISSUE TITLE
Post to default sim missing content type yields a request with no body

### ISSUE THREAD

**Issue by Shnick** [passivsystems/protean#199] opened 2016-07-28 21:40 UTC

**Comment by rossputin** [comment] 2016-08-05 09:12
Fixed if the request includes a Content-Type header in the codex, but should|can this be inferred to avoid the confusing empty body ?

**Comment by colin-passiv** [comment] 2016-08-16 10:21
Duplicate of #142 ?

**Comment by rossputin** [comment] 2016-08-16 11:30
Good spot - closing, ta.

**Closed by rossputin** 2016-08-16 11:30 UTC
